### ISSUE TITLE
Build failure in FreeBSD

### ISSUE THREAD

**Issue by zoomosis** [huskyproject/fidoconf#12]
Hello,

fidoconf does not build on FreeBSD because it looks for gcc, which does not exist (FreeBSD uses clang).

```
$ cd fidoconf
$ gmake

gcc -Wall -c -s -O3 -fomit-frame-pointer -fstrength-reduce -fPIC -O3 -DUNIX  -DCFGDIR=\"/home/fidonet/husky/etc/fido\" -DPATH_DELIM=\'/\' -c -fPIC -Wall -ggdb -DUNIX -I.. -Wno-char-subscripts -Ifidoconf -I/home/fidonet/husky/include src/common.c
gmake: gcc: Command not found
gmake: *** [makefile.inc:27: common.o] Error 127
```

The problem is Makefile includes makefile.in2, which clobbers $(CC) from ../huskymak.cfg.

This fixes it:

```
diff --git a/makefile.in2 b/makefile.in2
index 760af3a..c24fc8f 100755
--- a/makefile.in2
+++ b/makefile.in2
@@ -2,7 +2,7 @@
 # (legacy makefile, no dynlibs, no huskymak support)
 # this file is only a include file included by other files.

-CC   = gcc
+#CC   = gcc
 EXENAMEFLAG = -o
 AR   = ar
 AR_R = rs
```

Though I don't understand why makefile.in2 is included by Makefile at all if it's intended for legacy builds.

**Comment by dukelsky** [comment]
Your fix will break build for other OSes

**Comment by zoomosis** [comment]
I don't believe so. CC is already defined:

1. in ../huskymak.cfg
2. by GNU Make on all OSes

However if you insist:
```
ifndef CC
CC   = gcc
endif
```

**Comment by zoomosis** [comment]
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

CC is an implicit rule.

**Comment by dukelsky** [comment]
OK
