### ISSUE TITLE
 Areafixhelp and FileFixHelp are not recognized by current fidoconf

### ISSUE THREAD

**Issue by Manjago** [huskyproject/fidoconf#9]
Bad example - Areafixhelp and FileFixHelp are not recognized by current fidoconf

```
Areafixhelp     /home/mtt/fido/hpt/misc/areafix.hlp
FileFixHelp     /home/mtt/fido/htick/misc/filefix.hlp
```

**Comment by dukelsky** [comment]
Please open a pull request with your corrections

**Comment by dukelsky** [comment]
An addition to my previous comment.
If the issue is in the wiki please correct doc/fidoconfig.texi and not the wiki. Here is how to make a pull request:
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
